In [35]:
import pandas as pd 
import numpy as np
df=pd.read_csv('players_20.csv')

In [36]:
df


sofifa_id                                         player_url  \
0         158023  https://sofifa.com/player/158023/lionel-messi/...   
1          20801  https://sofifa.com/player/20801/c-ronaldo-dos-...   
2         190871  https://sofifa.com/player/190871/neymar-da-sil...   
3         200389  https://sofifa.com/player/200389/jan-oblak/20/...   
4         183277  https://sofifa.com/player/183277/eden-hazard/2...   
...          ...                                                ...   
18273     245006  https://sofifa.com/player/245006/shuai-shao/20...   
18274     250995  https://sofifa.com/player/250995/mingjie-xiao/...   
18275     252332  https://sofifa.com/player/252332/wei-zhang/20/...   
18276     251110  https://sofifa.com/player/251110/haijian-wang/...   
18277     233449  https://sofifa.com/player/233449/ximing-pan/20...   

              short_name                            long_name  age  \
0               L. Messi       Lionel Andrés Messi Cuccittini   32   
1      Cristiano Ronaldo  Cristiano Ronaldo dos Santos Aveiro   34   
2              Neymar Jr        Neymar da Silva Santos Junior   27   
3               J. Oblak                            Jan Oblak   26   
4              E. Hazard                          Eden Hazard   28   
...                  ...                                  ...  ...   
18273         Shao Shuai                                   邵帅   22   
18274       Xiao Mingjie                         Mingjie Xiao   22   
18275          Zhang Wei                                   张威   19   
18276       Wang Haijian                                  汪海健   18   
18277         Pan Ximing                                  潘喜明   26   

              dob  height_cm  weight_kg nationality  \
0      1987-06-24        170         72   Argentina   
1      1985-02-05        187         83    Portugal   
2      1992-02-05        175         68      Brazil   
3      1993-01-07        188         87    Slovenia   
4      1991-01-07        175         74     Belgium   
...           ...        ...        ...         ...   
18273  1997-03-10        186         79    China PR   
18274  1997-01-01        177         66    China PR   
18275  2000-05-16        186         75    China PR   
18276  2000-08-02        185         74    China PR   
18277  1993-01-11        182         78    China PR   

                                club  ...   lwb   ldm   cdm   rdm   rwb    lb  \
0                       FC Barcelona  ...  68+2  66+2  66+2  66+2  68+2  63+2   
1                           Juventus  ...  65+3  61+3  61+3  61+3  65+3  61+3   
2                Paris Saint-Germain  ...  66+3  61+3  61+3  61+3  66+3  61+3   
3                    Atlético Madrid  ...   NaN   NaN   NaN   NaN   NaN   NaN   
4                        Real Madrid  ...  66+3  63+3  63+3  63+3  66+3  61+3   
...                              ...  ...   ...   ...   ...   ...   ...   ...   
18273               Beijing Renhe FC  ...  43+2  42+2  42+2  42+2  43+2  45+2   
18274               Shanghai SIPG FC  ...  44+2  43+2  43+2  43+2  44+2  46+2   
18275         Hebei China Fortune FC  ...  47+2  49+2  49+2  49+2  47+2  47+2   
18276  Shanghai Greenland Shenhua FC  ...  48+2  48+2  48+2  48+2  48+2  48+2   
18277         Hebei China Fortune FC  ...  48+2  49+2  49+2  49+2  48+2  48+2   

        lcb    cb   rcb    rb  
0      52+2  52+2  52+2  63+2  
1      53+3  53+3  53+3  61+3  
2      46+3  46+3  46+3  61+3  
3       NaN   NaN   NaN   NaN  
4      49+3  49+3  49+3  61+3  
...     ...   ...   ...   ...  
18273  46+2  46+2  46+2  45+2  
18274  47+2  47+2  47+2  46+2  
18275  49+2  49+2  49+2  47+2  
18276  49+2  49+2  49+2  48+2  
18277  50+2  50+2  50+2  48+2  

[18278 rows x 104 columns]

In [104]:
##check for missing data
df.isnull().sum()

sofifa_id        0
player_url       0
short_name       0
long_name        0
age              0
              ... 
lb            2036
lcb           2036
cb            2036
rcb           2036
rb            2036
Length: 104, dtype: int64

In [106]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
encoder = LabelEncoder()
categorical_data=df['preferred_foot']
categorical_encoded=encoder.fit_transform(categorical_data)
print(categorical_encoded)
###
encoderr = OneHotEncoder()
categorical_data_hot= encoderr.fit_transform(categorical_encoded.reshape(-1,1))
categorical_data_hot.toarray()


[0 1 1 ... 1 1 1]


array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [107]:
encoder = LabelEncoder()
work_rate_en= df['work_rate']
categorical_encoded_wr=encoder.fit_transform(work_rate_en)
print(categorical_encoded_wr)
###
encoderrr = OneHotEncoder()
categorical_data_hot_wr= encoderrr.fit_transform(categorical_encoded_wr.reshape(-1,1))
categorical_data_hot_wr.toarray()



[7 1 2 ... 5 4 8]


array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [5]:
#player stat features
columns = ['overall','attacking_crossing', 'attacking_finishing', 'attacking_heading_accuracy', 'attacking_short_passing', 'attacking_volleys', 'skill_dribbling', 'skill_curve', 'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control', 'movement_acceleration', 'movement_sprint_speed', 'movement_agility', 'movement_reactions', 'movement_balance', 'power_shot_power', 'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots', 'mentality_aggression', 'mentality_interceptions', 'mentality_positioning', 'mentality_vision', 'mentality_penalties', 'mentality_composure', 'defending_marking', 'defending_standing_tackle', 'defending_sliding_tackle', 'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking', 'goalkeeping_positioning', 'goalkeeping_reflexes']
FIFA_data = df[columns]
FIFA_data.head()

overall  attacking_crossing  attacking_finishing  \
0       94                  88                   95   
1       93                  84                   94   
2       92                  87                   87   
3       91                  13                   11   
4       91                  81                   84   

   attacking_heading_accuracy  attacking_short_passing  attacking_volleys  \
0                          70                       92                 88   
1                          89                       83                 87   
2                          62                       87                 87   
3                          15                       43                 13   
4                          61                       89                 83   

   skill_dribbling  skill_curve  skill_fk_accuracy  skill_long_passing  ...  \
0               97           93                 94                  92  ...   
1               89           81                 76                  77  ...   
2               96           88                 87                  81  ...   
3               12           13                 14                  40  ...   
4               95           83                 79                  83  ...   

   mentality_penalties  mentality_composure  defending_marking  \
0                   75                   96                 33   
1                   85                   95                 28   
2                   90                   94                 27   
3                   11                   68                 27   
4                   88                   91                 34   

   defending_standing_tackle  defending_sliding_tackle  goalkeeping_diving  \
0                         37                        26                   6   
1                         32                        24                   7   
2                         26                        29                   9   
3                         12                        18                  87   
4                         27                        22                  11   

   goalkeeping_handling  goalkeeping_kicking  goalkeeping_positioning  \
0                    11                   15                       14   
1                    11                   15                       14   
2                     9                   15                       15   
3                    92                   78                       90   
4                    12                    6                        8   

   goalkeeping_reflexes  
0                     8  
1                    11  
2                    11  
3                    89  
4                     8  

[5 rows x 35 columns]

In [38]:
correlation=FIFA_data.corr()['overall'].sort_values(ascending=False)

##absolute value
abs_corr=abs(correlation)

###selecting relavant feature
relavant_features = pd.DataFrame(abs_corr[abs_corr>0.05])
relavant_features

overall
overall                  1.000000
movement_reactions       0.864526
mentality_composure      0.719992
power_shot_power         0.567504
mentality_vision         0.509251
attacking_short_passing  0.503157
skill_ball_control       0.457052
power_long_shots         0.425081
skill_curve              0.415521

In [77]:
#taking the important features and other relevant features
columns = ["overall","movement_reactions","mentality_composure","power_shot_power","mentality_vision","attacking_short_passing","skill_ball_control","power_long_shots","skill_curve","value_eur","age","movement_acceleration","potential","skill_long_passing"]
FIFA_data = df[columns]
FIFA_data.head()

overall  movement_reactions  mentality_composure  power_shot_power  \
0       94                  95                   96                86   
1       93                  96                   95                95   
2       92                  92                   94                80   
3       91                  88                   68                59   
4       91                  90                   91                82   

   mentality_vision  attacking_short_passing  skill_ball_control  \
0                94                       92                  96   
1                82                       83                  92   
2                90                       87                  95   
3                65                       43                  30   
4                89                       89                  94   

   power_long_shots  skill_curve  value_eur  age  movement_acceleration  \
0                94           93   95500000   32                     91   
1                93           81   58500000   34                     89   
2                84           88  105500000   27                     94   
3                12           13   77500000   26                     43   
4                80           83   90000000   28                     94   

   potential  skill_long_passing  
0         94                  92  
1         93                  77  
2         92                  81  
3         93                  40  
4         91                  83

In [78]:
X = FIFA_data.drop('overall',axis=1)
Y = FIFA_data['overall']

In [79]:
X.head()

movement_reactions  mentality_composure  power_shot_power  \
0                  95                   96                86   
1                  96                   95                95   
2                  92                   94                80   
3                  88                   68                59   
4                  90                   91                82   

   mentality_vision  attacking_short_passing  skill_ball_control  \
0                94                       92                  96   
1                82                       83                  92   
2                90                       87                  95   
3                65                       43                  30   
4                89                       89                  94   

   power_long_shots  skill_curve  value_eur  age  movement_acceleration  \
0                94           93   95500000   32                     91   
1                93           81   58500000   34                     89   
2                84           88  105500000   27                     94   
3                12           13   77500000   26                     43   
4                80           83   90000000   28                     94   

   potential  skill_long_passing  
0         94                  92  
1         93                  77  
2         92                  81  
3         93                  40  
4         91                  83

In [80]:
Y.head()

0    94
1    93
2    92
3    91
4    91
Name: overall, dtype: int64

In [81]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
scale = MinMaxScaler()

In [82]:
scal = MinMaxScaler()
scaled = scal.fit_transform(X,Y)
scaled

array([[0.98666667, 1.        , 0.88888889, ..., 0.92941176, 0.97826087,
        1.        ],
       [1.        , 0.98809524, 1.        , ..., 0.90588235, 0.95652174,
        0.82142857],
       [0.94666667, 0.97619048, 0.81481481, ..., 0.96470588, 0.93478261,
        0.86904762],
       ...,
       [0.41333333, 0.32142857, 0.41975309, ..., 0.50588235, 0.15217391,
        0.55952381],
       [0.44      , 0.33333333, 0.39506173, ..., 0.50588235, 0.10869565,
        0.47619048],
       [0.37333333, 0.35714286, 0.33333333, ..., 0.49411765, 0.04347826,
        0.52380952]])

In [83]:
corr_matrix = FIFA_data.corr()
corr_matrix

overall  movement_reactions  mentality_composure  \
overall                  1.000000            0.864526             0.719992   
movement_reactions       0.864526            1.000000             0.694967   
mentality_composure      0.719992            0.694967             1.000000   
power_shot_power         0.567504            0.523219             0.616498   
mentality_vision         0.509251            0.517061             0.650544   
attacking_short_passing  0.503157            0.499506             0.717620   
skill_ball_control       0.457052            0.456299             0.706688   
power_long_shots         0.425081            0.436887             0.645677   
skill_curve              0.415521            0.423051             0.640294   
value_eur                0.638230            0.556465             0.457112   
age                      0.464305            0.463331             0.370149   
movement_acceleration    0.186320            0.191985             0.372836   
potential                0.646650            0.517508             0.444101   
skill_long_passing       0.487289            0.477243             0.672855   

                         power_shot_power  mentality_vision  \
overall                          0.567504          0.509251   
movement_reactions               0.523219          0.517061   
mentality_composure              0.616498          0.650544   
power_shot_power                 1.000000          0.674526   
mentality_vision                 0.674526          1.000000   
attacking_short_passing          0.576883          0.705144   
skill_ball_control               0.619397          0.713004   
power_long_shots                 0.799835          0.757447   
skill_curve                      0.676858          0.746594   
value_eur                        0.356146          0.365560   
age                              0.261916          0.195372   
movement_acceleration            0.352961          0.458604   
potential                        0.349043          0.348782   
skill_long_passing               0.530542          0.694247   

                         attacking_short_passing  skill_ball_control  \
overall                                 0.503157            0.457052   
movement_reactions                      0.499506            0.456299   
mentality_composure                     0.717620            0.706688   
power_shot_power                        0.576883            0.619397   
mentality_vision                        0.705144            0.713004   
attacking_short_passing                 1.000000            0.917721   
skill_ball_control                      0.917721            1.000000   
power_long_shots                        0.766848            0.838259   
skill_curve                             0.778343            0.834229   
value_eur                               0.333462            0.307797   
age                                     0.135681            0.088359   
movement_acceleration                   0.568534            0.678317   
potential                               0.366478            0.347098   
skill_long_passing                      0.896180            0.792637   

                         power_long_shots  skill_curve  value_eur       age  \
overall                          0.425081     0.415521   0.638230  0.464305   
movement_reactions               0.436887     0.423051   0.556465  0.463331   
mentality_composure              0.645677     0.640294   0.457112  0.370149   
power_shot_power                 0.799835     0.676858   0.356146  0.261916   
mentality_vision                 0.757447     0.746594   0.365560  0.195372   
attacking_short_passing          0.766848     0.778343   0.333462  0.135681   
skill_ball_control               0.838259     0.834229   0.307797  0.088359   
power_long_shots                 1.000000     0.840344   0.277631  0.161616   
skill_curve                      0.840344     1.000000   0.285154  0.141891   
value_eur                        0.277

In [84]:
correlation = corr_matrix["overall"].sort_values(ascending=False)

In [85]:
FIFA_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18278 entries, 0 to 18277
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   overall                  18278 non-null  int64
 1   movement_reactions       18278 non-null  int64
 2   mentality_composure      18278 non-null  int64
 3   power_shot_power         18278 non-null  int64
 4   mentality_vision         18278 non-null  int64
 5   attacking_short_passing  18278 non-null  int64
 6   skill_ball_control       18278 non-null  int64
 7   power_long_shots         18278 non-null  int64
 8   skill_curve              18278 non-null  int64
 9   value_eur                18278 non-null  int64
 10  age                      18278 non-null  int64
 11  movement_acceleration    18278 non-null  int64
 12  potential                18278 non-null  int64
 13  skill_long_passing       18278 non-null  int64
dtypes: int64(14)
memory usage: 2.0 MB


In [86]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(FIFA_data, test_size=0.2, random_state=42)
print(len(train_set), "train +", len(test_set), "test")

14622 train + 3656 test


In [87]:
Xtrain,Xtest,Ytrain,Ytest = train_test_split(scaled,Y,test_size=0.2, random_state=42)

In [88]:
Xtrain.shape

(14622, 13)

In [89]:
Ytrain.shape

(14622,)

In [90]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(Xtrain,Ytrain)

LinearRegression()

In [91]:
lm = LinearRegression()
model = lm.fit(X,Y)
predictions = lm.predict(X)

In [92]:
model =  LinearRegression()
model.fit(Xtrain,Ytrain)

LinearRegression()

In [93]:
y_predict = model.predict(Xtest)
y_predict

array([65.8650771 , 73.86375235, 67.89517604, ..., 58.37383419,
       59.2036674 , 67.73535942])

In [94]:
from sklearn import metrics
print('MAE:', metrics.mean_absolute_error(Ytest, y_predict))
print('MSE:', metrics.mean_squared_error(Ytest, y_predict))
print('RMSE:', np.sqrt(metrics.mean_squared_error(Ytest, y_predict)))

MAE: 1.6001212332139039
MSE: 4.224968849651454
RMSE: 2.055472901706917


In [95]:
#validating model for linear regression
from sklearn.model_selection import cross_val_score
scores = cross_val_score(lin_reg, Xtrain, Ytrain,scoring='neg_mean_squared_error', cv=10)
lin_reg_scores = np.sqrt(-scores)
def display_scores(scores):
  print("Scores:", scores)
  print("Mean:", scores.mean())
  print("Standard Deviation:", scores.std())
display_scores(lin_reg_scores)

Scores: [2.10330812 2.04465065 2.09013023 2.15889035 2.07250689 2.03373623
 2.0863975  2.09417915 2.06015468 2.08868638]
Mean: 2.0832640183163913
Standard Deviation: 0.03304597413215482


In [96]:
from sklearn.tree import DecisionTreeRegressor
tree_reg = DecisionTreeRegressor()
tree_reg.fit(Xtrain, Ytrain)

DecisionTreeRegressor()

In [97]:
from sklearn.metrics import mean_squared_error
FIFA_predictions = tree_reg.predict(Xtrain)
tree_mse = mean_squared_error(Ytrain, FIFA_predictions)
tree_rmse = np.sqrt(tree_mse)
tree_rmse

0.0

In [98]:
#validating model for decision tree
scores = cross_val_score(tree_reg, Xtrain, Ytrain,
scoring='neg_mean_squared_error', cv=10)
tree_scores = np.sqrt(-scores)
display_scores(tree_scores)

Scores: [0.61034598 0.64306596 0.55725534 0.58888473 0.62220648 0.53470526
 0.56457192 0.54421469 0.5824614  0.58480532]
Mean: 0.5832517086587632
Standard Deviation: 0.03281688645861118


In [99]:
from sklearn.ensemble import RandomForestRegressor
forest_reg = RandomForestRegressor()
forest_reg.fit(Xtrain, Ytrain)

RandomForestRegressor()

In [100]:
FIFA_predictions = forest_reg.predict(Xtrain)
forest_mse = mean_squared_error(Ytrain, FIFA_predictions)
forest_rmse = np.sqrt(forest_mse)
forest_rmse

0.1457699737305905

In [101]:
##validating model for random forest
scores = cross_val_score(forest_reg, Xtrain, Ytrain,
scoring='neg_mean_squared_error', cv=10)
forest_scores = np.sqrt(-scores)
display_scores(forest_scores)

Scores: [0.42097363 0.497578   0.37522889 0.42518926 0.36938158 0.36036746
 0.37364017 0.36416302 0.41328826 0.38455386]
Mean: 0.39843641221052944
Standard Deviation: 0.04010927024813981


In [102]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error

In [108]:
#Training using xgboost
data_dmatrix = xgb.DMatrix(data=X,label=Y)

In [109]:
xg_reg = xgb.XGBRegressor(objective ='reg:linear', colsample_bytree = 0.3, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 10)

In [110]:
xg_reg.fit(Xtrain,Ytrain)
preds = xg_reg.predict(Xtest)

[15:27:38] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/objective/regression_obj.cu:188: reg:linear is now deprecated in favor of reg:squarederror.


In [111]:
rmse = np.sqrt(mean_squared_error(Ytest, preds))
print("RMSE: %f" % (rmse))

RMSE: 23.264734


In [112]:
#validating xgbost
params = {"objective":"reg:linear",'colsample_bytree': 0.3,'learning_rate': 0.1,
                'max_depth': 5, 'alpha': 10}

cv_results = xgb.cv(dtrain=data_dmatrix, params=params, nfold=3,
                    num_boost_round=50,early_stopping_rounds=10,metrics="rmse", as_pandas=True, seed=123)

[15:27:40] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/objective/regression_obj.cu:188: reg:linear is now deprecated in favor of reg:squarederror.
[15:27:40] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/objective/regression_obj.cu:188: reg:linear is now deprecated in favor of reg:squarederror.
[15:27:40] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/objective/regression_obj.cu:188: reg:linear is now deprecated in favor of reg:squarederror.


In [113]:
cv_results.head()

train-rmse-mean  train-rmse-std  test-rmse-mean  test-rmse-std
0        59.543600        0.024119       59.545082       0.046898
1        53.628002        0.019662       53.633273       0.054838
2        48.287417        0.018684       48.294717       0.053739
3        43.492796        0.003047       43.500017       0.058641
4        39.174801        0.009762       39.181709       0.058914

In [114]:
import joblib
joblib.dump(forest_reg,'model.pkl')

['model.pkl']

In [116]:
#testing data 
FIFA_15 = pd.read_csv("players_15.csv")
FIFA_15.head()

sofifa_id                                         player_url  \
0     158023  https://sofifa.com/player/158023/lionel-messi/...   
1      20801  https://sofifa.com/player/20801/c-ronaldo-dos-...   
2       9014  https://sofifa.com/player/9014/arjen-robben/15...   
3      41236  https://sofifa.com/player/41236/zlatan-ibrahim...   
4     167495  https://sofifa.com/player/167495/manuel-neuer/...   

          short_name                            long_name  age         dob  \
0           L. Messi       Lionel Andrés Messi Cuccittini   27  1987-06-24   
1  Cristiano Ronaldo  Cristiano Ronaldo dos Santos Aveiro   29  1985-02-05   
2          A. Robben                         Arjen Robben   30  1984-01-23   
3     Z. Ibrahimović                   Zlatan Ibrahimović   32  1981-10-03   
4           M. Neuer                         Manuel Neuer   28  1986-03-27   

   height_cm  weight_kg  nationality                 club  ...   lwb   ldm  \
0        169         67    Argentina         FC Barcelona  ...  62+3  62+3   
1        185         80     Portugal          Real Madrid  ...  63+3  63+3   
2        180         80  Netherlands    FC Bayern München  ...  64+3  64+3   
3        195         95       Sweden  Paris Saint-Germain  ...  61+3  65+3   
4        193         92      Germany    FC Bayern München  ...   NaN   NaN   

    cdm   rdm   rwb    lb   lcb    cb   rcb    rb  
0  62+3  62+3  62+3  54+3  45+3  45+3  45+3  54+3  
1  63+3  63+3  63+3  57+3  52+3  52+3  52+3  57+3  
2  64+3  64+3  64+3  55+3  46+3  46+3  46+3  55+3  
3  65+3  65+3  61+3  56+3  55+3  55+3  55+3  56+3  
4   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[5 rows x 104 columns]

In [117]:
FIFA_15.fillna(0,inplace=True)
FIFA_15.head()

sofifa_id                                         player_url  \
0     158023  https://sofifa.com/player/158023/lionel-messi/...   
1      20801  https://sofifa.com/player/20801/c-ronaldo-dos-...   
2       9014  https://sofifa.com/player/9014/arjen-robben/15...   
3      41236  https://sofifa.com/player/41236/zlatan-ibrahim...   
4     167495  https://sofifa.com/player/167495/manuel-neuer/...   

          short_name                            long_name  age         dob  \
0           L. Messi       Lionel Andrés Messi Cuccittini   27  1987-06-24   
1  Cristiano Ronaldo  Cristiano Ronaldo dos Santos Aveiro   29  1985-02-05   
2          A. Robben                         Arjen Robben   30  1984-01-23   
3     Z. Ibrahimović                   Zlatan Ibrahimović   32  1981-10-03   
4           M. Neuer                         Manuel Neuer   28  1986-03-27   

   height_cm  weight_kg  nationality                 club  ...   lwb   ldm  \
0        169         67    Argentina         FC Barcelona  ...  62+3  62+3   
1        185         80     Portugal          Real Madrid  ...  63+3  63+3   
2        180         80  Netherlands    FC Bayern München  ...  64+3  64+3   
3        195         95       Sweden  Paris Saint-Germain  ...  61+3  65+3   
4        193         92      Germany    FC Bayern München  ...     0     0   

    cdm   rdm   rwb    lb   lcb    cb   rcb    rb  
0  62+3  62+3  62+3  54+3  45+3  45+3  45+3  54+3  
1  63+3  63+3  63+3  57+3  52+3  52+3  52+3  57+3  
2  64+3  64+3  64+3  55+3  46+3  46+3  46+3  55+3  
3  65+3  65+3  61+3  56+3  55+3  55+3  55+3  56+3  
4     0     0     0     0     0     0     0     0  

[5 rows x 104 columns]

In [121]:
columns = ["overall","movement_reactions","mentality_composure","power_shot_power","mentality_vision","attacking_short_passing","skill_ball_control","power_long_shots","skill_curve","value_eur","age","movement_acceleration","potential","skill_long_passing"]
FIFA_15 = df[columns]
FIFA_15.head()

overall  movement_reactions  mentality_composure  power_shot_power  \
0       94                  95                   96                86   
1       93                  96                   95                95   
2       92                  92                   94                80   
3       91                  88                   68                59   
4       91                  90                   91                82   

   mentality_vision  attacking_short_passing  skill_ball_control  \
0                94                       92                  96   
1                82                       83                  92   
2                90                       87                  95   
3                65                       43                  30   
4                89                       89                  94   

   power_long_shots  skill_curve  value_eur  age  movement_acceleration  \
0                94           93   95500000   32                     91   
1                93           81   58500000   34                     89   
2                84           88  105500000   27                     94   
3                12           13   77500000   26                     43   
4                80           83   90000000   28                     94   

   potential  skill_long_passing  
0         94                  92  
1         93                  77  
2         92                  81  
3         93                  40  
4         91                  83

In [122]:
x = FIFA_15.drop('overall',axis=1)
y = FIFA_15['overall']

In [123]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
scale = MinMaxScaler()

In [124]:
scal = MinMaxScaler()
scaled = scal.fit_transform(X,Y)
scaled

array([[0.98666667, 1.        , 0.88888889, ..., 0.92941176, 0.97826087,
        1.        ],
       [1.        , 0.98809524, 1.        , ..., 0.90588235, 0.95652174,
        0.82142857],
       [0.94666667, 0.97619048, 0.81481481, ..., 0.96470588, 0.93478261,
        0.86904762],
       ...,
       [0.41333333, 0.32142857, 0.41975309, ..., 0.50588235, 0.15217391,
        0.55952381],
       [0.44      , 0.33333333, 0.39506173, ..., 0.50588235, 0.10869565,
        0.47619048],
       [0.37333333, 0.35714286, 0.33333333, ..., 0.49411765, 0.04347826,
        0.52380952]])

In [125]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(FIFA_15, test_size=0.2, random_state=42)
print(len(train_set), "train +", len(test_set), "test")

14622 train + 3656 test


In [126]:
xtrain,xtest,ytrain,ytest = train_test_split(scaled,y,test_size=0.2, random_state=42)

In [127]:
# Use the forest's predict method on the test data
predictions =forest_reg .predict(xtest)

In [128]:
# Calculate the absolute errors
errors = abs(predictions - ytest)

In [129]:
# Print out the mean absolute error (mae)
print('Mean Absolute Error:', round(np.mean(errors), 2), 'degrees.')

Mean Absolute Error: 0.21 degrees.


In [130]:
# Calculate mean absolute percentage error (MAPE)
mape = 100 * (errors / ytest)
# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')

Accuracy: 99.67 %.
